version: '3'
services:
  docker_jizero:
    container_name: docker_jizero
    build: ./
    ports:
      - "8083:8083"
    depends_on: 
      - fpm
    volumes:
      - ./data:/data
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - redis
      - fpm
    restart: always
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
    volumes:
      - ./redis_data/data:/data      
  fpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./data:/data

